### ISSUE TITLE
Publishing the provider to the Terraform registry

### ISSUE THREAD

**Issue by nyuen** [yaegashi/terraform-provider-msgraph#1]
Hi,

The provider looks great, you can now publish your Terraform Community Provider with Hashicorp. It would be great to get yours in the list.

I'm happy to help you with this as we would like to use your provider in our open source project : https://github.com/azure/caf-terraform-landingzones 

@arnaudlh, @LaurentLesle

**Comment by yaegashi** [comment]
Hi, thanks for reaching out.  I'm glad you like it.

Yes, it would be nice if we could see msgraph provider in the registry.  It's also appropriate for the next short term milestone in the development.

I really appreciate your suggestion and your help in future!

**Comment by hieunhums** [comment]
Hi @yaegashi, thank you for creating this great MS Graph provider.
I really want to use it to manage MS AD group and deletion. However providers are needed to published on TF registry for remote reference? 

You could have a look into provider self publishing on the registry at https://www.terraform.io/docs/registry/providers/publishing.html#publishing-to-the-registry
Is there any way I can help out to publish this?

**Comment by yaegashi** [comment]
@hieumoscow Thanks for pinging me...

I've noticed that now I can proceed to my public key registration (it was closed when I visited last week), but got an unknown error on submit.

Probably I have to contact people in HashiCorp.  I'll update you soon when I get an answer.

![image](https://user-images.githubusercontent.com/106724/88631851-cccc7780-d0ed-11ea-8a3e-7d17be0dd871.png)

The key I submit was:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEXxX1WRYJKwYBBAHaRw8BAQdAhI8aNo/uy7YUFI+TGnoANkt5Ie0f4pksNF4W
Rx41sGK0JVlBRUdBU0hJIFRha2VzaGkgPHlhZWdhc2hpQGdtYWlsLmNvbT6IkAQT
FggAOBYhBBVdMZR63bMR1bC/MvVysv40KKL7BQJfFfVZAhsDBQsJCAcCBhUKCQgL
AgQWAgMBAh4BAheAAAoJEPVysv40KKL7bUIBAMKG0IOiL0mW6fZH4MBXyEwHaU1c
AdNvNhjVb83AsuzXAQDJMYgm1MjSCsgtBW0Zp/o8fsC0lzHSv/N1+BmHI+DKDbg4
BF8V9VkSCisGAQQBl1UBBQEBB0Cobs7WFyQyUbHngnYi2LnTapWdWNLn5lKwPMwt
3GXJFwMBCAeIeAQYFggAIBYhBBVdMZR63bMR1bC/MvVysv40KKL7BQJfFfVZAhsM
AAoJEPVysv40KKL7TrQA/3aTWgG8ShPznEZypUjgj+Ng5IOYJ+amqJyWM3D+AReE
AP9ufTNEe6chd+jNxvfHbfEe6igTPAVSPWJO7m1jSKFAAw==
=agVY
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by yaegashi** [comment]
@hieumoscow Finally! https://registry.terraform.io/providers/yaegashi/msgraph

HashiCorp staff told me the registry has no support for Ed25519 GPG key.  So I had to recreate an RSA4096 key and rerelease v0.0.5 with it.  Another stumble point was https://github.com/crazy-max/ghaction-import-gpg doesn't support GPG subkeys for signing at all.  I wasted much time and randomness entropy on generating keys of different kinds to confirm that.

@nyuen I really appreciate your contribution with this issue and PR #4, and my apologies that it took so long time to be released.  Hope this provider is useful for you.

**Comment by nyuen** [comment]
Congrats that's awesome - I expect it will be very popular internally and with our customers and partners!

**Comment by hieunhums** [comment]
Woohoo that's awesome!
Thank you @yaegashi, we will work on integrating this into our project now and let you know

**Comment by arnaudlh** [comment]
Nice work! great news indeed!
